FROM fosfora/bridge-base

LABEL org.opencontainers.image.description="Fosfora Smart LFO Bridge"

COPY bridges/smart_lfo.py .

ENTRYPOINT ["python", "smart_lfo.py"]
CMD ["--host", "host.docker.internal"]
